// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_duIeb4d-t0_2CXINdQJALIPFaEyWR_o',
    appId: '1:56479086475:web:76eefda291ea4e7dcda18e',
    messagingSenderId: '56479086475',
    projectId: 'soiree-18fad',
    authDomain: 'soiree-18fad.firebaseapp.com',
    storageBucket: 'soiree-18fad.appspot.com',
    measurementId: 'G-0EFTPQ9V9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdS96TCBnOQo2hMA3I_iXrrSsbDNg6KI',
    appId: '1:56479086475:android:7b0b34164b959b3acda18e',
    messagingSenderId: '56479086475',
    projectId: 'soiree-18fad',
    storageBucket: 'soiree-18fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3U8ujlt4JJxEKViwU-nwVgBjgGLgmQeI',
    appId: '1:56479086475:ios:bff7aad8e8a0ad87cda18e',
    messagingSenderId: '56479086475',
    projectId: 'soiree-18fad',
    storageBucket: 'soiree-18fad.appspot.com',
    iosClientId: '56479086475-l1a4ah9do7aglo4tqobeje9jft5htneo.apps.googleusercontent.com',
    iosBundleId: 'com.example.soiree',
  );
}
